/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\RedMaserati.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/RedMaserati.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.097}>
          <mesh geometry={nodes.Object_21.geometry} material={materials.Grille3A} />
          <mesh geometry={nodes.Object_23.geometry} material={materials.GlassClear} />
          <mesh geometry={nodes.Object_25.geometry} material={materials.GlassRed} />
          <mesh geometry={nodes.Object_27.geometry} material={materials.Grille4A} />
          <mesh geometry={nodes.Object_29.geometry} material={materials.Grille7A} />
          <mesh geometry={nodes.Object_31.geometry} material={materials.Grille6A} />
          <mesh geometry={nodes.Object_33.geometry} material={materials.Grille5A} />
          <mesh geometry={nodes.Object_35.geometry} material={materials.InteriorColor2} />
          <mesh geometry={nodes.Object_37.geometry} material={materials.InteriorColor2Opacity} />
          <mesh geometry={nodes.Object_39.geometry} material={materials.InteriorColor1Opacity} />
          <mesh geometry={nodes.Object_41.geometry} material={materials.InteriorColor1} />
          <mesh geometry={nodes.Object_43.geometry} material={materials.InteriorTillingColourZoneA} />
          <mesh geometry={nodes.Object_45.geometry} material={materials.InteriorTilling} />
          <mesh geometry={nodes.Object_47.geometry} material={materials.Lights} />
          <mesh geometry={nodes.Object_49.geometry} material={materials.Paint} />
          <mesh geometry={nodes.Object_51.geometry} material={materials.CaliperColor} />
          <mesh geometry={nodes.Object_53.geometry} material={materials.CaliperTextured} />
          <mesh geometry={nodes.Object_55.geometry} material={materials.CalliperBadgeA} />
          <mesh geometry={nodes.Object_57.geometry} material={materials.Coloured} />
          <mesh geometry={nodes.Object_59.geometry} material={materials.Coloured} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.Base} />
          <mesh geometry={nodes.Object_61.geometry} material={materials.Carbon1} />
          <mesh geometry={nodes.Object_63.geometry} material={materials.InteriorBase} />
          <mesh geometry={nodes.Object_65.geometry} material={materials.InteriorBase} />
          <mesh geometry={nodes.Object_67.geometry} material={materials.InteriorBaseOpacity} />
          <mesh geometry={nodes.Object_69.geometry} material={materials.WindowDark} />
          <mesh geometry={nodes.Object_71.geometry} material={materials.Window} />
          <mesh geometry={nodes.Object_73.geometry} material={materials.Wheel1A} />
          <mesh geometry={nodes.Object_75.geometry} material={materials.Wheel1A} />
          <mesh geometry={nodes.Object_77.geometry} material={materials.Wheel2A} />
          <mesh geometry={nodes.Object_79.geometry} material={materials.Wheel2A} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.BadgeA} />
          <mesh geometry={nodes.Object_81.geometry} material={materials.Wheel3A} />
          <mesh geometry={nodes.Object_83.geometry} material={materials.Wheel3A} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.Engine} />
          <mesh geometry={nodes.Object_13.geometry} material={materials.GlassAmber} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.EngineOpacity} />
          <mesh geometry={nodes.Object_17.geometry} material={materials.Grille2A} />
          <mesh geometry={nodes.Object_19.geometry} material={materials.Grille1A} />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.097}>
          <mesh geometry={nodes.Object_21001.geometry} material={materials['Grille3A.001']} />
          <mesh geometry={nodes.Object_23001.geometry} material={materials['GlassClear.001']} />
          <mesh geometry={nodes.Object_25001.geometry} material={materials['GlassRed.001']} />
          <mesh geometry={nodes.Object_27001.geometry} material={materials['Grille4A.001']} />
          <mesh geometry={nodes.Object_29001.geometry} material={materials['Grille7A.001']} />
          <mesh geometry={nodes.Object_31001.geometry} material={materials['Grille6A.001']} />
          <mesh geometry={nodes.Object_33001.geometry} material={materials['Grille5A.001']} />
          <mesh geometry={nodes.Object_35001.geometry} material={materials['InteriorColor2.001']} />
          <mesh geometry={nodes.Object_37001.geometry} material={materials['InteriorColor2Opacity.001']} />
          <mesh geometry={nodes.Object_39001.geometry} material={materials['InteriorColor1Opacity.001']} />
          <mesh geometry={nodes.Object_41001.geometry} material={materials['InteriorColor1.001']} />
          <mesh geometry={nodes.Object_43001.geometry} material={materials['InteriorTillingColourZoneA.001']} />
          <mesh geometry={nodes.Object_45001.geometry} material={materials['InteriorTilling.001']} />
          <mesh geometry={nodes.Object_47001.geometry} material={materials['Lights.001']} />
          <mesh geometry={nodes.Object_49001.geometry} material={materials['Paint.001']} />
          <mesh geometry={nodes.Object_51001.geometry} material={materials['CaliperColor.001']} />
          <mesh geometry={nodes.Object_53001.geometry} material={materials['CaliperTextured.001']} />
          <mesh geometry={nodes.Object_55001.geometry} material={materials['CalliperBadgeA.001']} />
          <mesh geometry={nodes.Object_57001.geometry} material={materials['Coloured.001']} />
          <mesh geometry={nodes.Object_59001.geometry} material={materials['Coloured.001']} />
          <mesh geometry={nodes.Object_7001.geometry} material={materials['Base.001']} />
          <mesh geometry={nodes.Object_61001.geometry} material={materials['Carbon1.001']} />
          <mesh geometry={nodes.Object_63001.geometry} material={materials['InteriorBase.001']} />
          <mesh geometry={nodes.Object_65001.geometry} material={materials['InteriorBase.001']} />
          <mesh geometry={nodes.Object_67001.geometry} material={materials['InteriorBaseOpacity.001']} />
          <mesh geometry={nodes.Object_69001.geometry} material={materials['WindowDark.001']} />
          <mesh geometry={nodes.Object_71001.geometry} material={materials['Window.001']} />
          <mesh geometry={nodes.Object_73001.geometry} material={materials['Wheel1A.001']} />
          <mesh geometry={nodes.Object_75001.geometry} material={materials['Wheel1A.001']} />
          <mesh geometry={nodes.Object_77001.geometry} material={materials['Wheel2A.001']} />
          <mesh geometry={nodes.Object_79001.geometry} material={materials['Wheel2A.001']} />
          <mesh geometry={nodes.Object_9001.geometry} material={materials['BadgeA.001']} />
          <mesh geometry={nodes.Object_81001.geometry} material={materials['Wheel3A.001']} />
          <mesh geometry={nodes.Object_83001.geometry} material={materials['Wheel3A.001']} />
          <mesh geometry={nodes.Object_11001.geometry} material={materials['Engine.001']} />
          <mesh geometry={nodes.Object_13001.geometry} material={materials['GlassAmber.001']} />
          <mesh geometry={nodes.Object_15001.geometry} material={materials['EngineOpacity.001']} />
          <mesh geometry={nodes.Object_17001.geometry} material={materials['Grille2A.001']} />
          <mesh geometry={nodes.Object_19001.geometry} material={materials['Grille1A.001']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/RedMaserati.gltf')
