/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\WhiteLambo.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/WhiteLambo.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={1.687}>
        <group scale={0.01}>
          <group position={[0.006, 0, -0.069]} scale={0.1}>
            <mesh geometry={nodes.Object_327.geometry} material={materials.CarPaintBlack_1_299} />
            <mesh geometry={nodes.Object_329.geometry} material={materials.DettagliSedile_300} />
          </group>
          <mesh geometry={nodes.Object_332.geometry} material={materials.Griglia04_1_377_2} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_335.geometry} material={materials.Griglia04_1_377_2} position={[0.006, 0, -0.069]} scale={0.1} />
          <group position={[0.006, 0, -0.069]} scale={0.1}>
            <mesh geometry={nodes.Object_340.geometry} material={materials.AlcantaraVerde_238} />
            <mesh geometry={nodes.Object_338.geometry} material={materials.NeroLowGloss_307} />
          </group>
          <group position={[0.006, 0, -0.069]} scale={0.1}>
            <mesh geometry={nodes.Object_345.geometry} material={materials.AlcantaraVerde_308} />
            <mesh geometry={nodes.Object_343.geometry} material={materials.NeroLowGloss_307} />
          </group>
          <mesh geometry={nodes.Object_348.geometry} material={materials.NeroLowGloss_307} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_351.geometry} material={materials.NeroLowGloss_307} position={[0.006, 0, -0.069]} scale={0.1} />
          <group position={[0.006, 0, -0.069]} scale={0.1}>
            <mesh geometry={nodes.Object_358.geometry} material={materials['AlcantaraScuro_314.2']} />
            <mesh geometry={nodes.Object_360.geometry} material={materials.AlcantaraVerde_315_0} />
            <mesh geometry={nodes.Object_354.geometry} material={materials.CarnonFiber_363_0} />
            <mesh geometry={nodes.Object_356.geometry} material={materials.Interior_291_0} />
          </group>
          <mesh geometry={nodes.Object_363.geometry} material={materials.Tappetino_DX_316} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_366.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_41.geometry} material={materials.Car_Paint_0} position={[0.09, -0.142, 0.878]} />
          <mesh geometry={nodes.Object_369.geometry} material={materials.InteriorTiling01_311} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_372.geometry} material={materials['Mat.1']} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_375.geometry} material={materials.Griglia04_1_377_1} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_378.geometry} material={materials.Griglia04_1_377} position={[0.006, 1.593, 0.819]} scale={0.1} />
          <mesh geometry={nodes.Object_381.geometry} material={materials.Griglia04_1_377} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_384.geometry} material={materials.Car_Paint_0} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_387.geometry} material={materials.Griglia01_343_0} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_390.geometry} material={materials.Griglia04_1_377_2} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_393.geometry} material={materials.Griglia04_1_377_2} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_396.geometry} material={materials.Car_Paint_0} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_44.geometry} material={materials.Car_Paint_0} position={[255.835, 35.167, -0.763]} />
          <mesh geometry={nodes.Object_399.geometry} material={materials.PolygonObject120__0} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_402.geometry} material={materials.Griglia01_343_1} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_405.geometry} material={materials.PolygonObject120__0} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_408.geometry} material={materials.Griglia04_1_377} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_411.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_414.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_417.geometry} material={materials.Griglia04_1_377} position={[0.006, 1.762, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_420.geometry} material={materials.Tappetino_SX_334} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_423.geometry} material={materials.Car_Paint_0} position={[0.006, 0, -0.069]} />
          <mesh geometry={nodes.Object_426.geometry} material={materials.AlcantaraVerde_315_1} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_47.geometry} material={materials.Wheels} scale={[0.1, 0.105, 0.1]} />
          <mesh geometry={nodes.Object_429.geometry} material={materials.AlcantaraVerde_315_1} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_432.geometry} material={materials.AlcantaraVerde_315_1} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_435.geometry} material={materials.AlcantaraVerde_315_1} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_438.geometry} material={materials.Griglia01_343} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_441.geometry} material={materials.Griglia01_343_2} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_444.geometry} material={materials.Griglia01_343} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_447.geometry} material={materials.AlcantaraVerde_315_1} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_450.geometry} material={materials.Griglia04_1_377_3} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_453.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_456.geometry} material={materials.Griglia04_1_377_2} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_50.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_459.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_462.geometry} material={materials.Griglia04_1_377_2} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_465.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_468.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_471.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_474.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_477.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_480.geometry} material={materials.Tappetino_SX_334_0} position={[0.006, 0, -0.069]} scale={0.1} />
          <group position={[0.006, 0, -0.069]} scale={0.1}>
            <mesh geometry={nodes.Object_483.geometry} material={materials.PolygonObject120__0} />
            <mesh geometry={nodes.Object_485.geometry} material={materials.CarPaintBlack_1_299} />
          </group>
          <group position={[0.006, 0, -0.069]} scale={0.1}>
            <mesh geometry={nodes.Object_488.geometry} material={materials.PolygonObject120__0} />
            <mesh geometry={nodes.Object_490.geometry} material={materials.CarPaintBlack_1_299} />
          </group>
          <mesh geometry={nodes.Object_53.geometry} material={materials.Car_Paint} position={[0.006, 0, -0.069]} scale={0.1} />
          <group position={[0.006, 0, -0.069]} scale={0.1}>
            <mesh geometry={nodes.Object_495.geometry} material={materials.CarPaintBlack_1_299} />
            <mesh geometry={nodes.Object_493.geometry} material={materials.Griglia04_1_377_2} />
          </group>
          <group position={[0.006, 0, -0.069]} scale={0.1}>
            <mesh geometry={nodes.Object_500.geometry} material={materials.CarPaintBlack_1_299} />
            <mesh geometry={nodes.Object_498.geometry} material={materials.Griglia04_1_377_2} />
          </group>
          <group position={[0.006, 0, -0.069]} scale={0.1}>
            <mesh geometry={nodes.Object_505.geometry} material={materials.CarPaintBlack_1_299} />
            <mesh geometry={nodes.Object_503.geometry} material={materials.Griglia04_1_377_2} />
          </group>
          <mesh geometry={nodes.Object_508.geometry} material={materials.Car_Paint_0} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_511.geometry} material={materials.PolygonObject120__0} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_514.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_517.geometry} material={materials.BlackShader_2_384} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_520.geometry} material={materials.BlackShader_2_384} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_523.geometry} material={materials.BlackShader_2_384} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_526.geometry} material={materials.BlackShader_2_384} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_56.geometry} material={materials.BlackShader_2_384} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_529.geometry} material={materials.BlackShader_2_384} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_532.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_535.geometry} material={materials.Car_Paint_0} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_538.geometry} material={materials.PolygonObject120__0} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_541.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_544.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_547.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_550.geometry} material={materials.PolygonObject120__0} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_553.geometry} material={materials.Interior_291} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_556.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_59.geometry} material={materials.Griglia04_1_377} position={[0.006, 1.593, 0.819]} scale={0.1} />
          <mesh geometry={nodes.Object_559.geometry} material={materials.Car_Paint_0} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_62.geometry} material={materials.Griglia04_1_377} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_65.geometry} material={materials.BlackShader_2_384_0} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_68.geometry} material={materials.BlackShader_2_384_0} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.Car_Paint} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_71.geometry} material={materials.BlackShader_2_384} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_74.geometry} material={materials.Griglia04_1_377} position={[0.006, 1.593, 0.819]} scale={0.1} />
          <mesh geometry={nodes.Object_77.geometry} material={materials.Griglia04_1_377} position={[0.006, 1.762, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_80.geometry} material={materials.Griglia04_1_377} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_83.geometry} material={materials.Griglia04_1_377} position={[0.006, 0, -0.069]} scale={0.1} />
          <group position={[0.006, 0, -0.069]} scale={0.1}>
            <mesh geometry={nodes.Object_86.geometry} material={materials.CarnonFiber_363} />
            <mesh geometry={nodes.Object_88.geometry} material={materials.NeroLowGloss_307} />
          </group>
          <group position={[0.006, 0, -0.069]} scale={0.1}>
            <mesh geometry={nodes.Object_91.geometry} material={materials.CarnonFiber_363} />
            <mesh geometry={nodes.Object_93.geometry} material={materials.NeroLowGloss_307} />
          </group>
          <mesh geometry={nodes.Object_96.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_99.geometry} material={materials.Wheels} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_102.geometry} material={materials.Car_Paint_0} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.Car_Paint} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_105.geometry} material={materials.Wheels} position={[256.87, 34.84, -0.069]} scale={[0.11, 0.11, 0.1]} />
          <mesh geometry={nodes.Object_108.geometry} material={materials.Interior_291} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_111.geometry} material={materials.Interior_291} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_114.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_117.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_120.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_123.geometry} material={materials.Car_Paint_0} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_126.geometry} material={materials.Car_Paint_0} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_129.geometry} material={materials.Griglia01_343} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_132.geometry} material={materials.Car_Paint} position={[0.006, 0, -0.069]} scale={0.1} />
          <group position={[-1.109, 0, 0.023]} scale={0.1}>
            <mesh geometry={nodes.Object_14.geometry} material={materials.Car_Paint} />
            <mesh geometry={nodes.Object_16.geometry} material={materials.Car_Paint_0} />
          </group>
          <mesh geometry={nodes.Object_135.geometry} material={materials.Car_Paint} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_138.geometry} material={materials.Griglia04_1_377_0} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_141.geometry} material={materials.GrigliaSpeaker_226} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_144.geometry} material={materials.GrigliaSpeaker_226} position={[0.006, 0, -0.069]} scale={0.1} />
          <group position={[0.006, 0, -0.069]} scale={0.1}>
            <mesh geometry={nodes.Object_147.geometry} material={materials.AlcantaraScuro_231} />
            <mesh geometry={nodes.Object_149.geometry} material={materials.AlcantaraVerde_238} />
          </group>
          <group position={[0.006, 0, -0.069]} scale={0.1}>
            <mesh geometry={nodes.Object_154.geometry} material={materials.AlcantaraScuro_231} />
            <mesh geometry={nodes.Object_156.geometry} material={materials.AlcantaraVerde_238} />
            <mesh geometry={nodes.Object_152.geometry} material={materials.Interior_291} />
          </group>
          <mesh geometry={nodes.Object_159.geometry} material={materials.AlcantaraVerde_238} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_162.geometry} material={materials.Car_Paint} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_165.geometry} material={materials.Car_Paint} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_168.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_19.geometry} material={materials.Car_Paint} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_171.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_174.geometry} material={materials.AlcantaraVerde_238} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_177.geometry} material={materials['AlcantaraScuro_314.2']} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_180.geometry} material={materials.Car_Paint_0} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_183.geometry} material={materials.AlcantaraVerde_315} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_186.geometry} material={materials.Car_Paint_0} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_189.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_192.geometry} material={materials.Griglia04_1_377_1} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_195.geometry} material={materials.Car_Paint} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_198.geometry} material={materials.GlassGoogle_001_258} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.Car_Paint} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_201.geometry} material={materials.GlassGoogle_001_258} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_204.geometry} material={materials.GlassGoogle_001_258} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_207.geometry} material={materials.GrigliaSpeaker_260} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_210.geometry} material={materials.GrigliaSpeaker_260} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_213.geometry} material={materials.Griglia04_1_377_2} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_216.geometry} material={materials.Griglia04_1_377_2} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_219.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_222.geometry} material={materials.Car_Paint_0} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_225.geometry} material={materials.Car_Paint_0} position={[0.006, 0, -0.069]} />
          <mesh geometry={nodes.Object_228.geometry} material={materials.Car_Paint_0} position={[0.006, 0, -0.069]} scale={0.1} />
          <group position={[0.006, 0, -0.069]} scale={0.1}>
            <mesh geometry={nodes.Object_29.geometry} material={materials['AlcantaraScuro_314.2']} />
            <mesh geometry={nodes.Object_25.geometry} material={materials.Car_Paint} />
            <mesh geometry={nodes.Object_27.geometry} material={materials.Car_Paint_0} />
          </group>
          <mesh geometry={nodes.Object_231.geometry} material={materials.Car_Paint_0} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_234.geometry} material={materials.Car_Paint} position={[0.006, 0, -0.069]} scale={0.1} />
          <group position={[0.006, 0, -0.069]} scale={0.1}>
            <mesh geometry={nodes.Object_237.geometry} material={materials.Car_Paint} />
            <mesh geometry={nodes.Object_239.geometry} material={materials.Car_Paint_0} />
          </group>
          <mesh geometry={nodes.Object_242.geometry} material={materials.BlackGlossy_266} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_245.geometry} material={materials.GrigliaSpeaker_260} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_248.geometry} material={materials.Car_Paint} position={[0.006, 1.762, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_251.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_254.geometry} material={materials.Car_Paint_0} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_257.geometry} material={materials.Car_Paint_0} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_260.geometry} material={materials.Car_Paint_0} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_32.geometry} material={materials.Car_Paint_0} position={[76.536, 38.631, 0]} />
          <group position={[0.006, 0, -0.069]} scale={0.1}>
            <mesh geometry={nodes.Object_263.geometry} material={materials.Car_Paint} />
            <mesh geometry={nodes.Object_265.geometry} material={materials.Car_Paint_0} />
          </group>
          <mesh geometry={nodes.Object_268.geometry} material={materials.Car_Paint_0} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_271.geometry} material={materials['material.002']} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_274.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_277.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_280.geometry} material={materials.AlcantaraScuro_231} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_283.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_286.geometry} material={materials.Griglia04_1_377_2} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_289.geometry} material={materials.Car_Paint} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_292.geometry} material={materials.Car_Paint} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_295.geometry} material={materials.Car_Paint_0} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_298.geometry} material={materials.Car_Paint} position={[0.008, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_301.geometry} material={materials.Interior_291} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_304.geometry} material={materials.CarPaintBlack_1_299} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_307.geometry} material={materials.Car_Paint} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_310.geometry} material={materials.AlcantaraVerde_238} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_313.geometry} material={materials.AlcantaraVerde_238} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_316.geometry} material={materials.Griglia04_1_377_2} position={[0.006, 0, -0.069]} scale={0.1} />
          <mesh geometry={nodes.Object_319.geometry} material={materials.Griglia04_1_377_2} position={[0.006, 0, -0.069]} scale={0.1} />
          <group position={[0.006, 0, -0.069]} scale={0.1}>
            <mesh geometry={nodes.Object_322.geometry} material={materials.CarPaintBlack_1_299} />
            <mesh geometry={nodes.Object_324.geometry} material={materials.DettagliSedile_300} />
          </group>
          <mesh geometry={nodes.Object_38.geometry} material={materials.Car_Paint_0} position={[-97.781, 29.468, 0.095]} />
          <mesh geometry={nodes.Object_35.geometry} material={materials.Car_Paint_0} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/WhiteLambo.gltf')
